= Matcha

== Glossary

WSGI:: https://en.wikipedia.org/wiki/Web_Server_Gateway_Interface[Web Server Gateway Interface]

== Frameworks

=== Frontend

* https://angular.dev/[Angular]

=== Database

* https://www.postgresql.org/[PostgreSQL]

=== Backend

* https://flask.palletsprojects.com/en/3.0.x/quickstart/[Flask] as WSGI
* https://www.psycopg.org/[psycopg] as adapter between Python and PostgreSQL
* https://black.readthedocs.io/en/stable/index.html#[black] as code formatter

== TODO

Browser

filter
par 4 values

- max age gap + and - value
- max distance km
- fame rating

Report a user as a “fake account”.
- create array of user I set as fake

/profile
- user
- interest
- email
- pictures

=> create endpoint get-user-profile with all data for profile

- profile complete

=> create two

will never send
- password
- id

get all user

full profile
. check id

GET sans rien

=> JWT -> id -> all data

GET all users

=> gender + sexual preference

- flag button
- like button

Populate une DB

https://pypi.org/project/flask-websockets/

Sanitize les inputs du backend

- add age to users

=== email verified

. register
. backend send an email confirmation

user confirm: he is allow to reset password when he foret

user do not confirm: he can't get new password

== Python review

add an underscore to say that the function is private

for optimisation, avoid loop for and while

vectorise the code

example: filter a file.
instead to read line by line,
read column by column

DRY
avoid to reapeat piece of code
to avoid to change at many places

python string template

----
>>> from string import Template
>>> t = Template('x is $x')
>>> t.substitute({'x' : 1})
'x is 1'
----

https://docs.pytest.org/en/stable/[pytest] VS https://docs.python.org/3/library/unittest.html[unitest]

https://pytest-cov.readthedocs.io/en/latest/readme.html[pytest-co]

avoid to have dead code
test every part of code

TODO:

- unit test
- create a folder test
  in folder test, create a file with the same name of the file to test
- type the argument type

----
def (age : int) -> int : 
	return 12
----

- avoid to explicitly return None
here : https://github.com/t-h2o/matcha/blob/e7239fd40aa48abfc753437d0187d9a1d318421a/backend/matcha/db.py#L191

IDEA:

- centralize error message
