FROM python:3.9-alpine

WORKDIR /app

RUN apk add --no-cache postgresql-dev gcc python3-dev musl-dev

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 5000

ENV FLASK_APP=matcha
ENV FLASK_RUN_HOST=0.0.0.0

CMD ["flask", "--debug", "run", "--host=0.0.0.0", "--port=5000"]
