Project matcha {
  database_type: 'PostgreSQL'
  Note: 'matcha'
}

Table users {
  id integer [primary key, unique]
  username varchar [unique, not null]
}

Table user_biography {
  id_user integer [fk]
  biography varchar
}

Table user_gender {
  id_user integer [fk]
  gender varchar(1) [not null]
}

Table user_createdat {
  id_user integer [fk]
  created_at timestamp
}

Table sexualpreference {
  id integer [primary key, unique]
  sexualpreference varchar
}

Table interest {
  id integer [primary key, unique]
  interest varchar
}

Table picture {
  id integer [primary key, unique]
  picture_path varchar
}

Table picture_profile {
  id_picture integer [fk]
  is_profile_picture boolean [default false]
}

Table user_interest {
  id_user integer [fk]
  id_interest integer [fk]
}

Table user_picture {
  id_user integer [fk]
  id_picture integer [fk]
}

Table user_sexualpreference {
  id_user integer [fk]
  id_sexualpreference integer [fk]
}
