export let dummyUserData = {
  username: 'JohnnyAppleseed',
  firstName: 'Johnny',
  lastName: 'Appleseed',
  email: 'JohnnyAppleseed@test.com',
  gender: 'male',
  sexualPreference: 'heterosexual',
  birthDate: '1990-01-01',
  bio: 'I am a very interesting person. I like to do interesting things and go to interesting places. I am looking for someone who is also interesting.',
  interests: [
    'hiking',
    'biking',
    'swimming',
    'reading',
    'cooking',
    'traveling',
  ],
  pictures: [
    'johnnyAppleseed1',
    'johnnyAppleseed2',
    'johnnyAppleseed3',
    'johnnyAppleseed4',
    'johnnyAppleseed5',
  ],
  profilePic: 'johnnyAppleseed1',
};
